name: hsa_app
description: Flutter project For LEAD Smart One App .
version: 1.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 系统
  url_launcher: 5.4.2
  package_info: 0.4.0+16
  device_info: 0.4.2+1
  # 工具
  encrypt: 3.3.1
  date_format: 1.0.8
  native_color: 1.2.0
  path_drawing: 0.4.1
  # 网络
  cached_network_image: 2.0.0
  flutter_cache_manager: 1.2.1
  dio: 3.0.9
  connectivity: 0.4.8
  webview_flutter: 0.3.19+9
  # 文件
  shared_preferences: 0.5.6+3
  path_provider: 1.6.5
  # 播放器
  flt_video_player: 0.0.4
  # 推送
  jpush_flutter: 0.0.13
  # 图表
  syncfusion_flutter_charts: 17.4.40
  # 统计
  lcfarm_flutter_umeng: 0.1.8
  # 状态管理
  flutter_bloc: 3.2.0
  # UI
  cupertino_icons: 0.1.3
  flutter_section_table_view: 1.0.5
  fluttertoast: 3.1.3
  flutter_spinkit: 4.1.2+1
  ovprogresshud: 0.2.5
  flutter_banner_swiper: 0.1.4
  loading: 1.0.2
  pull_to_refresh: 1.5.8
  pin_code_text_field: 1.5.1
  flutter_cupertino_data_picker: 0.8.6
  progress_dialog: 1.2.2
  loading_indicator: 1.1.0
  page_view_indicator: 2.0.3
  flutter_cupertino_date_picker: 1.0.12
  wave: 0.0.8
  flui: 0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    
    # 身份验证公钥
    - keys/public.pem
    # 图片资源
    - images/
    - images/common/
    - images/history/
    - images/home/
    - images/login/
    - images/mine/
    - images/runtime/
    - images/station/
    - images/board/
    - images/about/
    - images/welcome/
    - images/banner/

  fonts:
    - family: ArialNarrow
      fonts:
        - asset: fonts/ArialNarrow.ttf

    - family: DINCondensedC
      fonts:
        - asset: fonts/DINCondensedC.ttf
