name: hsa_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter

  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.15+1
  cached_network_image: ^1.1.1
  shared_preferences: ^0.5.3+4
  event_bus: ^1.1.0
  equatable: ^0.4.0
  url_launcher: ^5.1.2
  sqlcool: ^3.2.0
  path_provider: ^1.2.0
  sqflite: ^1.1.6+3
  dio: ^3.0.3
  package_info: ^0.4.0+6
  encrypt: ^3.1.0
  flutter_section_table_view: ^1.0.5
  fluttertoast: ^3.1.2
  flutter_spinkit: ^4.0.0
  ovprogresshud: ^0.2.5
  event_taxi: ^0.1.5
  wave: ^0.0.8
  badges: ^1.1.0
  flutter_banner_swiper: ^0.1.4
  loading: ^1.0.1
  native_color: ^1.0.0
  path_drawing: ^0.4.1
  connectivity: ^0.4.5+3
  pull_to_refresh: ^1.5.7
  flt_video_player: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/common/
    - images/history/
    - images/home/
    - images/login/
    - images/mine/
    - images/runtime/
    - images/station/
    - images/board/
    - images/about/
    - images/welcome/
    - images/banner/

  fonts:
    - family: ArialNarrow
      fonts:
      - asset: fonts/ArialNarrow.ttf